# Generated by Django 2.0.6 on 2018-06-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('pay_out', models.IntegerField()),
                ('pay_in', models.IntegerField()),
            ],
        ),
    ]
