# Generated by Django 2.0.6 on 2018-06-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
